//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kando_desktop.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("kando_desktop.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableros Activos.
        /// </summary>
        public static string ActiveBoards {
            get {
                return ResourceManager.GetString("ActiveBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Ya tienes una cuenta?.
        /// </summary>
        public static string AlreadyAccount {
            get {
                return ResourceManager.GetString("AlreadyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Kando.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Tablero creado correctamente!.
        /// </summary>
        public static string BoardCreatedSuccessfully {
            get {
                return ResourceManager.GetString("BoardCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Tablero.
        /// </summary>
        public static string BoardName {
            get {
                return ResourceManager.GetString("BoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tableros.
        /// </summary>
        public static string Boards {
            get {
                return ResourceManager.GetString("Boards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tareas completadas.
        /// </summary>
        public static string CompletedTasks {
            get {
                return ResourceManager.GetString("CompletedTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear una cuenta.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear cuenta.
        /// </summary>
        public static string CreateAccountBtn {
            get {
                return ResourceManager.GetString("CreateAccountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Comienza administrando tus proyectos hoy.
        /// </summary>
        public static string CreateAccountSubtitle {
            get {
                return ResourceManager.GetString("CreateAccountSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Tablero.
        /// </summary>
        public static string CreateBoard {
            get {
                return ResourceManager.GetString("CreateBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Equipo.
        /// </summary>
        public static string CreateTeam {
            get {
                return ResourceManager.GetString("CreateTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Equipo.
        /// </summary>
        public static string DeleteTeam {
            get {
                return ResourceManager.GetString("DeleteTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Perfil.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tucorreo@ejemplo.com.
        /// </summary>
        public static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre del tablero....
        /// </summary>
        public static string EnterBoardName {
            get {
                return ResourceManager.GetString("EnterBoardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre del equipo....
        /// </summary>
        public static string EnterTeamName {
            get {
                return ResourceManager.GetString("EnterTeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al conectar con el servidor.
        /// </summary>
        public static string ErrorConnectingServer {
            get {
                return ResourceManager.GetString("ErrorConnectingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Campo obligatorio.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre Completo.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a John Doe.
        /// </summary>
        public static string FullNamePlaceholder {
            get {
                return ResourceManager.GetString("FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GitHub.
        /// </summary>
        public static string GitHubBtn {
            get {
                return ResourceManager.GetString("GitHubBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Google.
        /// </summary>
        public static string GoogleBtn {
            get {
                return ResourceManager.GetString("GoogleBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Icono.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string InviteButton {
            get {
                return ResourceManager.GetString("InviteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a eliminado exitosamente.
        /// </summary>
        public static string MemberRemovedFromTeam {
            get {
                return ResourceManager.GetString("MemberRemovedFromTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Modificar Equipo.
        /// </summary>
        public static string ModifyTeam {
            get {
                return ResourceManager.GetString("ModifyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Tablero.
        /// </summary>
        public static string NewBoardButton {
            get {
                return ResourceManager.GetString("NewBoardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Equipo.
        /// </summary>
        public static string NewTeamButton {
            get {
                return ResourceManager.GetString("NewTeamButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿No tienes una cuenta?.
        /// </summary>
        public static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay tableros.
        /// </summary>
        public static string NoBoards {
            get {
                return ResourceManager.GetString("NoBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un equipo o crea uno nuevo para añadir un tablero..
        /// </summary>
        public static string NoBoardsDescription {
            get {
                return ResourceManager.GetString("NoBoardsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No hay equipos.
        /// </summary>
        public static string NoTeams {
            get {
                return ResourceManager.GetString("NoTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crea un nuevo equipo para comenzar a colaborar..
        /// </summary>
        public static string NoTeamsDescription {
            get {
                return ResourceManager.GetString("NoTeamsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a O continuar con.
        /// </summary>
        public static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Progreso.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrarse.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar Integrante.
        /// </summary>
        public static string RemoveMember {
            get {
                return ResourceManager.GetString("RemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembro.
        /// </summary>
        public static string Role_Member {
            get {
                return ResourceManager.GetString("Role_Member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dueño.
        /// </summary>
        public static string Role_Owner {
            get {
                return ResourceManager.GetString("Role_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pendiente.
        /// </summary>
        public static string Role_Pending {
            get {
                return ResourceManager.GetString("Role_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar Cambios.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar tableros....
        /// </summary>
        public static string SearchBoards {
            get {
                return ResourceManager.GetString("SearchBoards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un equipo....
        /// </summary>
        public static string SelectTeam {
            get {
                return ResourceManager.GetString("SelectTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un equipo primero.
        /// </summary>
        public static string SelectTeamFirst {
            get {
                return ResourceManager.GetString("SelectTeamFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Organiza tu trabajo,.
        /// </summary>
        public static string SloganLine1 {
            get {
                return ResourceManager.GetString("SloganLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a amplifica tu impacto..
        /// </summary>
        public static string SloganLine2 {
            get {
                return ResourceManager.GetString("SloganLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El moderno administrador de proyectos.
        /// </summary>
        public static string SubSlogan {
            get {
                return ResourceManager.GetString("SubSlogan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a tareas.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color del Equipo.
        /// </summary>
        public static string TeamColor {
            get {
                return ResourceManager.GetString("TeamColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Equipo creado correctamente!.
        /// </summary>
        public static string TeamCreatedSuccessfully {
            get {
                return ResourceManager.GetString("TeamCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Miembros del Equipo -.
        /// </summary>
        public static string TeamMembers {
            get {
                return ResourceManager.GetString("TeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre del Equipo.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipos.
        /// </summary>
        public static string TeamsCount {
            get {
                return ResourceManager.GetString("TeamsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Equipo actualizado correctamente.
        /// </summary>
        public static string TeamUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("TeamUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido de nuevo.
        /// </summary>
        public static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa tus credenciales.
        /// </summary>
        public static string WelcomeSubtitle {
            get {
                return ResourceManager.GetString("WelcomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Bienvenido de vuelta!.
        /// </summary>
        public static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestiona tus equipos y proyectos en un solo lugar.
        /// </summary>
        public static string WorkspaceSubtitle {
            get {
                return ResourceManager.GetString("WorkspaceSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tu Espacio de Trabajo.
        /// </summary>
        public static string WorkspaceTitle {
            get {
                return ResourceManager.GetString("WorkspaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Tableros.
        /// </summary>
        public static string YourBoardsTitle {
            get {
                return ResourceManager.GetString("YourBoardsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tus Equipos.
        /// </summary>
        public static string YourTeamsTitle {
            get {
                return ResourceManager.GetString("YourTeamsTitle", resourceCulture);
            }
        }
    }
}
